# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'ApiAndModel' do
  pod 'Alamofire', '~> 2.0' 
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'ApiAndModelTests' do

end

target 'ApiAndModelUITests' do

end

