# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'randomstringTab' do

    pod 'Alamofire', '~> 2.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end

target 'randomstringTabTests' do

end

target 'randomstringTabUITests' do

end

