# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TodoAppWithCoreData' do
  pod "AFNetworking", "~> 2.0"
end

target 'TodoAppWithCoreDataTests' do

end

